# gen_payload.ps1 —— 生成 src/payload.h (MCCombatStatusJni.dll XOR 0x5A 加密载荷)
# 由 build.bat 在 DLL 编译后调用
$ErrorActionPreference = 'Stop'
$src = Join-Path $PSScriptRoot '..\MCCombatStatusJni.dll'
$out = Join-Path $PSScriptRoot '..\src\payload.h'
$b = [IO.File]::ReadAllBytes($src)
$e = New-Object byte[] $b.Length
for ($i = 0; $i -lt $b.Length; $i++) { $e[$i] = $b[$i] -bxor 0x5A }
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('// auto-generated by tools/gen_payload.ps1: MCCombatStatusJni.dll XOR 0x5A')
[void]$sb.AppendLine('static const unsigned char kPayload[] = {')
$row = '    '
for ($i = 0; $i -lt $e.Length; $i++) {
    $row += ('0x{0:X2}' -f $e[$i])
    if ($i -lt $e.Length - 1) { $row += ', ' }
    if (($i + 1) % 16 -eq 0) { [void]$sb.AppendLine($row); $row = '    ' }
}
if ($row.Trim() -ne '') { [void]$sb.AppendLine($row.TrimEnd(', ')) }
[void]$sb.AppendLine('};')
[void]$sb.AppendLine('static const unsigned int kPayloadLen = ' + $e.Length + ';')
[IO.File]::WriteAllText($out, $sb.ToString(), [System.Text.UTF8Encoding]::new($false))
Write-Host "payload.h: $($e.Length) bytes"
